In [1]:
from bs4 import BeautifulSoup as bs
from Bio import Entrez
import xmltodict
import urllib.request
from urllib.request import urlopen
import requests
import re
import pandas as pd
import csv
import openpyxl
import time
import numpy as np
from xlsxwriter.utility import xl_rowcol_to_cell
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options

import warnings
warnings.filterwarnings('ignore')

/tmp/ipykernel_9333/1986711241.py:8: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

# DATA FROM CANCER.GOV. Get drug names and corresponding page link

In [2]:
def get_drug_list(link,fname):
    r=requests.get(link).text
    s=bs(r,'lxml')
    article=s.find('article')
    if article != None:
    #print(article)
        d={'Drug_name':'Link'}
        a= article.find_all('ul', class_='no-bullets no-description')
        for i in a:
            for q in i.find_all('a',href=True):
                if len(q.get_text()) >1:
                    d[q.get_text()]=q['href'].rsplit('/', 1)[-1]
                    
    
    first_iter=True
    for i in d:
        if first_iter:
            first_iter = False
            continue
        q=d[i]
        d[i]= 'cancer.gov/about-cancer/treatment/drugs/' + q
        if 'selumetinib sulfate' in d[i]:
            d[i]= 'cancer.gov/about-cancer/treatment/drugs/selumetinibsulfate'
    for i in d:
        print(i+':'+d[i])
            
    df=pd.DataFrame.from_dict(d,orient='index')
    df.to_excel(fname,header=False)

In [4]:
#Parse Cancer.gov and get drug list
get_drug_list('https://www.cancer.gov/about-cancer/treatment/drugs','cancer_gov_drug_list.xlsx')
print('cancer_gov_drug_list Saved')

Drug_name:Link
Abecma (Idecabtagene Vicleucel):cancer.gov/about-cancer/treatment/drugs/idecabtagenevicleucel
Abemaciclib:cancer.gov/about-cancer/treatment/drugs/abemaciclib
Abiraterone Acetate:cancer.gov/about-cancer/treatment/drugs/abirateroneacetate
Abraxane (Paclitaxel Albumin-stabilized Nanoparticle Formulation):cancer.gov/about-cancer/treatment/drugs/nanoparticlepaclitaxel
ABVD:cancer.gov/about-cancer/treatment/drugs/abvd
ABVE:cancer.gov/about-cancer/treatment/drugs/abve
ABVE-PC:cancer.gov/about-cancer/treatment/drugs/abve-pc
AC:cancer.gov/about-cancer/treatment/drugs/ac
Acalabrutinib:cancer.gov/about-cancer/treatment/drugs/acalabrutinib
AC-T:cancer.gov/about-cancer/treatment/drugs/ac-t
Actemra (Tocilizumab):cancer.gov/about-cancer/treatment/drugs/tocilizumab
Adagrasib:cancer.gov/about-cancer/treatment/drugs/adagrasib
Adcetris (Brentuximab Vedotin):cancer.gov/about-cancer/treatment/drugs/brentuximabvedotin
ADE:cancer.gov/about-cancer/treatment/drugs/ade
Ado-Trastuzumab Emtansine:cancer.gov/about-cancer/treatment/drugs/ado-trastuzumab-emtansine
Adriamycin (Doxorubicin Hydrochloride):cancer.gov/about-cancer/treatment/drugs/doxorubicinhydrochloride
Adstiladrin (Nadofaragene Firadenovec-vncg):cancer.gov/about-cancer/treatment/drugs/nadofaragene-firadenovec-vncg
Afatinib Dimaleate:cancer.gov/about-cancer/treatment/drugs/afatinibdimaleate
Afinitor (Everolimus):cancer.gov/about-cancer/treatment/drugs/everolimus
Akeega (Niraparib Tosylate Monohydrate and Abiraterone Acetate):cancer.gov/about-cancer/treatment/drugs/niraparib-tosylate-monohydrate-and-abiraterone-acetate
Akynzeo (Netupitant and Palonosetron Hydrochloride):cancer.gov/about-cancer/treatment/drugs/netupitant-palonosetronhydrochloride
Aldara (Imiquimod):cancer.gov/about-cancer/treatment/drugs/imiquimod
Aldesleukin:cancer.gov/about-cancer/treatment/drugs/aldesleukin
Alecensa (Alectinib):cancer.gov/about-cancer/treatment/drugs/alectinib
Alectinib:cancer.gov/about-cancer/treatment/drugs/alectinib
Alemtuzumab:cancer.gov/about-cancer/treatment/drugs/alemtuzumab
Alimta (Pemetrexed Disodium):cancer.gov/about-cancer/treatment/drugs/pemetrexeddisodium
Alkeran for Injection (Melphalan Hydrochloride):cancer.gov/about-cancer/treatment/drugs/melphalan-hydrochloride
Alkeran Tablets (Melphalan):cancer.gov/about-cancer/treatment/drugs/melphalan
Aloxi (Palonosetron Hydrochloride):cancer.gov/about-cancer/treatment/drugs/palonosetronhydrochloride
Alpelisib:cancer.gov/about-cancer/treatment/drugs/alpelisib
Alunbrig (Brigatinib):cancer.gov/about-cancer/treatment/drugs/brigatinib
Alymsys (Bevacizumab):cancer.gov/about-cancer/treatment/drugs/bevacizumab
Ameluz (Aminolevulinic Acid Hydrochloride):cancer.gov/about-cancer/treatment/drugs/aminolevulinicacid
Amifostine:cancer.gov/about-cancer/treatment/drugs/amifostine
Aminolevulinic Acid Hydrochloride:cancer.gov/about-cancer/treatment/drugs/aminolevulinicacid
Amivantamab-vmjw:cancer.gov/about-cancer/treatment/drugs/amivantamab-vmjw
Anastrozole:cancer.gov/about-cancer/treatment/drugs/anastrozole
Apalutamide:cancer.gov/about-cancer/treatment/drugs/apalutamide
Aprepitant:cancer.gov/about-cancer/treatment/drugs/aprepitant
Aranesp (Darbepoetin Alfa):cancer.gov/about-cancer/treatment/drugs/darbepoetinalfa
Aredia (Pamidronate Disodium):cancer.gov/about-cancer/treatment/drugs/pamidronatedisodium
Arimidex (Anastrozole):cancer.gov/about-cancer/treatment/drugs/anastrozole
Aromasin (Exemestane):cancer.gov/about-cancer/treatment/drugs/exemestane
Arranon (Nelarabine):cancer.gov/about-cancer/treatment/drugs/nelarabine
Arsenic Trioxide:cancer.gov/about-cancer/treatment/drugs/arsenictrioxide
Arzerra (Ofatumumab):cancer.gov/about-cancer/treatment/drugs/ofatumumab
Asciminib Hydrochloride:cancer.gov/about-cancer/treatment/drugs/asciminib-hydrochloride
Asparaginase Erwinia Chrysanthemi:cancer.gov/about-cancer/treatment/drugs/asparaginase-erwinia-chrysanthemi
Asparaginase Erwinia Chrysanthemi (Recombinant)-rywn:cancer.gov/about-cancer/treatment/drugs/asparaginase-erwinia-chrysanthemi-recombinant
Asparlas (Calaspargase Pegol-mknl):cancer.gov/about-cancer/treatment/drugs/calaspargasepegol-mknl
Atezolizumab:cancer.gov/about-cancer/treatment/drugs/atezolizumab
Augtyro (Repotrectinib):cancer.gov/about-cancer/treatment/drugs/repotrectinib
Avapritinib:cancer.gov/about-cancer/treatment/drugs/avapritinib
Avastin (Bevacizumab):cancer.gov/about-cancer/treatment/drugs/bevacizumab
Avelumab:cancer.gov/about-cancer/treatment/drugs/avelumab
Axicabtagene Ciloleucel:cancer.gov/about-cancer/treatment/drugs/axicabtageneciloleucel
Axitinib:cancer.gov/about-cancer/treatment/drugs/axitinib
Ayvakit (Avapritinib):cancer.gov/about-cancer/treatment/drugs/avapritinib
Azacitidine:cancer.gov/about-cancer/treatment/drugs/azacitidine
Azedra (Iobenguane I 131):cancer.gov/about-cancer/treatment/drugs/iobenguanei131
Balversa (Erdafitinib):cancer.gov/about-cancer/treatment/drugs/erdafitinib
Bavencio (Avelumab):cancer.gov/about-cancer/treatment/drugs/avelumab
BEACOPP:cancer.gov/about-cancer/treatment/drugs/beacopp
Beleodaq (Belinostat):cancer.gov/about-cancer/treatment/drugs/belinostat
Belinostat:cancer.gov/about-cancer/treatment/drugs/belinostat
Belzutifan:cancer.gov/about-cancer/treatment/drugs/belzutifan
Bendamustine Hydrochloride:cancer.gov/about-cancer/treatment/drugs/bendamustinehydrochloride
Bendeka (Bendamustine Hydrochloride):cancer.gov/about-cancer/treatment/drugs/bendamustinehydrochloride
BEP:cancer.gov/about-cancer/treatment/drugs/bep
Besponsa (Inotuzumab Ozogamicin):cancer.gov/about-cancer/treatment/drugs/inotuzumabozogamicin
Besremi (Ropeginterferon Alfa-2b-njft):cancer.gov/about-cancer/treatment/drugs/ropeginterferon-alfa-2b-njft
Bevacizumab:cancer.gov/about-cancer/treatment/drugs/bevacizumab
Bexarotene:cancer.gov/about-cancer/treatment/drugs/bexarotene
Bicalutamide:cancer.gov/about-cancer/treatment/drugs/bicalutamide
BiCNU (Carmustine):cancer.gov/about-cancer/treatment/drugs/carmustine
Binimetinib:cancer.gov/about-cancer/treatment/drugs/binimetinib
Bleomycin Sulfate:cancer.gov/about-cancer/treatment/drugs/bleomycin
Blinatumomab:cancer.gov/about-cancer/treatment/drugs/blinatumomab
Blincyto (Blinatumomab):cancer.gov/about-cancer/treatment/drugs/blinatumomab
Bortezomib:cancer.gov/about-cancer/treatment/drugs/bortezomib
Bosulif (Bosutinib):cancer.gov/about-cancer/treatment/drugs/bosutinib
Bosutinib:cancer.gov/about-cancer/treatment/drugs/bosutinib
Braftovi (Encorafenib):cancer.gov/about-cancer/treatment/drugs/encorafenib
Brentuximab Vedotin:cancer.gov/about-cancer/treatment/drugs/brentuximabvedotin
Brexucabtagene Autoleucel:cancer.gov/about-cancer/treatment/drugs/brexucabtageneautoleucel
Breyanzi (Lisocabtagene Maraleucel):cancer.gov/about-cancer/treatment/drugs/lisocabtagenemaraleucel
Brigatinib:cancer.gov/about-cancer/treatment/drugs/brigatinib
Brukinsa (Zanubrutinib):cancer.gov/about-cancer/treatment/drugs/zanubrutinib
BuMel:cancer.gov/about-cancer/treatment/drugs/bumel
Busulfan:cancer.gov/about-cancer/treatment/drugs/busulfan
Busulfex (Busulfan):cancer.gov/about-cancer/treatment/drugs/busulfan
Cabazitaxel:cancer.gov/about-cancer/treatment/drugs/cabazitaxel
Cablivi (Caplacizumab-yhdp):cancer.gov/about-cancer/treatment/drugs/caplacizumab-yhdp
Cabometyx (Cabozantinib-S-Malate):cancer.gov/about-cancer/treatment/drugs/cabozantinib-s-malate
Cabozantinib-S-Malate:cancer.gov/about-cancer/treatment/drugs/cabozantinib-s-malate
CAF:cancer.gov/about-cancer/treatment/drugs/caf
Calaspargase Pegol-mknl:cancer.gov/about-cancer/treatment/drugs/calaspargasepegol-mknl
Calquence (Acalabrutinib):cancer.gov/about-cancer/treatment/drugs/acalabrutinib
Campath (Alemtuzumab):cancer.gov/about-cancer/treatment/drugs/alemtuzumab
Camptosar (Irinotecan Hydrochloride):cancer.gov/about-cancer/treatment/drugs/irinotecanhydrochloride
Capecitabine:cancer.gov/about-cancer/treatment/drugs/capecitabine
Capivasertib:cancer.gov/about-cancer/treatment/drugs/capivasertib
Caplacizumab-yhdp:cancer.gov/about-cancer/treatment/drugs/caplacizumab-yhdp
Capmatinib Hydrochloride:cancer.gov/about-cancer/treatment/drugs/capmatinibhydrochloride
CAPOX:cancer.gov/about-cancer/treatment/drugs/capox
Carac (Fluorouracil Topical):cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
Carboplatin:cancer.gov/about-cancer/treatment/drugs/carboplatin
CARBOPLATIN-TAXOL:cancer.gov/about-cancer/treatment/drugs/carboplatin-taxol
Carfilzomib:cancer.gov/about-cancer/treatment/drugs/carfilzomib
Carmustine:cancer.gov/about-cancer/treatment/drugs/carmustine
Carmustine Implant:cancer.gov/about-cancer/treatment/drugs/carmustineimplant
Carvykti (Ciltacabtagene Autoleucel):cancer.gov/about-cancer/treatment/drugs/ciltacabtagene-autoleucel
Casodex (Bicalutamide):cancer.gov/about-cancer/treatment/drugs/bicalutamide
CEM:cancer.gov/about-cancer/treatment/drugs/cem
Cemiplimab-rwlc:cancer.gov/about-cancer/treatment/drugs/cemiplimab-rwlc
Ceritinib:cancer.gov/about-cancer/treatment/drugs/ceritinib
Cervarix (Recombinant HPV Bivalent Vaccine):cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-bivalent-vaccine
Cetuximab:cancer.gov/about-cancer/treatment/drugs/cetuximab
CEV:cancer.gov/about-cancer/treatment/drugs/cev
Chlorambucil:cancer.gov/about-cancer/treatment/drugs/chlorambucil
CHLORAMBUCIL-PREDNISONE:cancer.gov/about-cancer/treatment/drugs/chlorambucil-prednisone
CHOP:cancer.gov/about-cancer/treatment/drugs/chop
Ciltacabtagene Autoleucel:cancer.gov/about-cancer/treatment/drugs/ciltacabtagene-autoleucel
Cisplatin:cancer.gov/about-cancer/treatment/drugs/cisplatin
Cladribine:cancer.gov/about-cancer/treatment/drugs/cladribine
Clofarabine:cancer.gov/about-cancer/treatment/drugs/clofarabine
Clolar (Clofarabine):cancer.gov/about-cancer/treatment/drugs/clofarabine
CMF:cancer.gov/about-cancer/treatment/drugs/cmf
Cobimetinib Fumarate:cancer.gov/about-cancer/treatment/drugs/cobimetinib
Columvi (Glofitamab-gxbm):cancer.gov/about-cancer/treatment/drugs/glofitamab-gxbm
Cometriq (Cabozantinib-S-Malate):cancer.gov/about-cancer/treatment/drugs/cabozantinib-s-malate
COPDAC:cancer.gov/about-cancer/treatment/drugs/copdac
Copiktra (Duvelisib):cancer.gov/about-cancer/treatment/drugs/duvelisib
COPP:cancer.gov/about-cancer/treatment/drugs/copp
COPP-ABV:cancer.gov/about-cancer/treatment/drugs/copp-abv
Cosmegen (Dactinomycin):cancer.gov/about-cancer/treatment/drugs/dactinomycin
Cotellic (Cobimetinib Fumarate):cancer.gov/about-cancer/treatment/drugs/cobimetinib
Crizotinib:cancer.gov/about-cancer/treatment/drugs/crizotinib
CVP:cancer.gov/about-cancer/treatment/drugs/cvp
Cyclophosphamide:cancer.gov/about-cancer/treatment/drugs/cyclophosphamide
Cyramza (Ramucirumab):cancer.gov/about-cancer/treatment/drugs/ramucirumab
Cytarabine:cancer.gov/about-cancer/treatment/drugs/cytarabine
Dabrafenib Mesylate:cancer.gov/about-cancer/treatment/drugs/dabrafenib
Dacarbazine:cancer.gov/about-cancer/treatment/drugs/dacarbazine
Dacogen (Decitabine):cancer.gov/about-cancer/treatment/drugs/decitabine
Dacomitinib:cancer.gov/about-cancer/treatment/drugs/dacomitinib
Dactinomycin:cancer.gov/about-cancer/treatment/drugs/dactinomycin
Danyelza (Naxitamab-gqgk):cancer.gov/about-cancer/treatment/drugs/naxitamab-gqgk
Daratumumab:cancer.gov/about-cancer/treatment/drugs/daratumumab
Daratumumab and Hyaluronidase-fihj:cancer.gov/about-cancer/treatment/drugs/daratumumabandhyaluronidase-fihj
Darbepoetin Alfa:cancer.gov/about-cancer/treatment/drugs/darbepoetinalfa
Darolutamide:cancer.gov/about-cancer/treatment/drugs/darolutamide
Darzalex (Daratumumab):cancer.gov/about-cancer/treatment/drugs/daratumumab
Darzalex Faspro (Daratumumab and Hyaluronidase-fihj):cancer.gov/about-cancer/treatment/drugs/daratumumabandhyaluronidase-fihj
Dasatinib:cancer.gov/about-cancer/treatment/drugs/dasatinib
Daunorubicin Hydrochloride:cancer.gov/about-cancer/treatment/drugs/daunorubicinhydrochloride
Daunorubicin Hydrochloride and Cytarabine Liposome:cancer.gov/about-cancer/treatment/drugs/daunorubicinhydrochlorideandcytarabineliposome
Daurismo (Glasdegib Maleate):cancer.gov/about-cancer/treatment/drugs/glasdegibmaleate
Decitabine:cancer.gov/about-cancer/treatment/drugs/decitabine
Decitabine and Cedazuridine:cancer.gov/about-cancer/treatment/drugs/decitabineandcedazuridine
Defibrotide Sodium:cancer.gov/about-cancer/treatment/drugs/defibrotide-sodium
Defitelio (Defibrotide Sodium):cancer.gov/about-cancer/treatment/drugs/defibrotide-sodium
Degarelix:cancer.gov/about-cancer/treatment/drugs/degarelix
Denileukin Diftitox:cancer.gov/about-cancer/treatment/drugs/denileukindiftitox
Denosumab:cancer.gov/about-cancer/treatment/drugs/denosumab
Dexamethasone:cancer.gov/about-cancer/treatment/drugs/dexamethasone
Dexrazoxane Hydrochloride:cancer.gov/about-cancer/treatment/drugs/dexrazoxanehydrochloride
Dinutuximab:cancer.gov/about-cancer/treatment/drugs/dinutuximab
Docetaxel:cancer.gov/about-cancer/treatment/drugs/docetaxel
Dostarlimab-gxly:cancer.gov/about-cancer/treatment/drugs/dostarlimab-gxly
Doxil (Doxorubicin Hydrochloride Liposome):cancer.gov/about-cancer/treatment/drugs/doxorubicin-hydrochloride-liposome
Doxorubicin Hydrochloride:cancer.gov/about-cancer/treatment/drugs/doxorubicinhydrochloride
Doxorubicin Hydrochloride Liposome:cancer.gov/about-cancer/treatment/drugs/doxorubicin-hydrochloride-liposome
Durvalumab:cancer.gov/about-cancer/treatment/drugs/durvalumab
Duvelisib:cancer.gov/about-cancer/treatment/drugs/duvelisib
Eflornithine Hydrochloride:cancer.gov/about-cancer/treatment/drugs/eflornithine-hydrochloride
Efudex (Fluorouracil Topical):cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
Elacestrant Dihydrochloride:cancer.gov/about-cancer/treatment/drugs/elacestrant-dihydrochloride
Elahere (Mirvetuximab Soravtansine-gynx):cancer.gov/about-cancer/treatment/drugs/mirvetuximab-soravtansine-gynx
Eligard (Leuprolide Acetate):cancer.gov/about-cancer/treatment/drugs/leuprolideacetate
Elitek (Rasburicase):cancer.gov/about-cancer/treatment/drugs/rasburicase
Ellence (Epirubicin Hydrochloride):cancer.gov/about-cancer/treatment/drugs/epirubicinhydrochloride
Elotuzumab:cancer.gov/about-cancer/treatment/drugs/elotuzumab
Eloxatin (Oxaliplatin):cancer.gov/about-cancer/treatment/drugs/oxaliplatin
Elranatamab-bcmm:cancer.gov/about-cancer/treatment/drugs/elranatamab-bcmm
Elrexfio (Elranatamab-bcmm):cancer.gov/about-cancer/treatment/drugs/elranatamab-bcmm
Eltrombopag Olamine:cancer.gov/about-cancer/treatment/drugs/eltrombopagolamine
Elzonris (Tagraxofusp-erzs):cancer.gov/about-cancer/treatment/drugs/tagraxofusp-erzs
Emapalumab-lzsg:cancer.gov/about-cancer/treatment/drugs/emapalumab-lzsg
Emend (Aprepitant):cancer.gov/about-cancer/treatment/drugs/aprepitant
Empliciti (Elotuzumab):cancer.gov/about-cancer/treatment/drugs/elotuzumab
Enasidenib Mesylate:cancer.gov/about-cancer/treatment/drugs/enasidenibmesylate
Encorafenib:cancer.gov/about-cancer/treatment/drugs/encorafenib
Enfortumab Vedotin-ejfv:cancer.gov/about-cancer/treatment/drugs/enfortumabvedotin-ejfv
Enhertu (Fam-Trastuzumab Deruxtecan-nxki):cancer.gov/about-cancer/treatment/drugs/famtrastuzumabderuxtecan-nxki
Entrectinib:cancer.gov/about-cancer/treatment/drugs/entrectinib
Enzalutamide:cancer.gov/about-cancer/treatment/drugs/enzalutamide
Epcoritamab-bysp:cancer.gov/about-cancer/treatment/drugs/epcoritamab-bysp
Epirubicin Hydrochloride:cancer.gov/about-cancer/treatment/drugs/epirubicinhydrochloride
Epkinly (Epcoritamab-bysp):cancer.gov/about-cancer/treatment/drugs/epcoritamab-bysp
EPOCH:cancer.gov/about-cancer/treatment/drugs/epoch
Epoetin Alfa:cancer.gov/about-cancer/treatment/drugs/epoetinalfa
Epogen (Epoetin Alfa):cancer.gov/about-cancer/treatment/drugs/epoetinalfa
Erbitux (Cetuximab):cancer.gov/about-cancer/treatment/drugs/cetuximab
Erdafitinib:cancer.gov/about-cancer/treatment/drugs/erdafitinib
Eribulin Mesylate:cancer.gov/about-cancer/treatment/drugs/eribulinmesylate
Erivedge (Vismodegib):cancer.gov/about-cancer/treatment/drugs/vismodegib
Erleada (Apalutamide):cancer.gov/about-cancer/treatment/drugs/apalutamide
Erlotinib Hydrochloride:cancer.gov/about-cancer/treatment/drugs/erlotinibhydrochloride
Erwinaze (Asparaginase Erwinia chrysanthemi):cancer.gov/about-cancer/treatment/drugs/asparaginase-erwinia-chrysanthemi
Ethyol (Amifostine):cancer.gov/about-cancer/treatment/drugs/amifostine
Etopophos (Etoposide Phosphate):cancer.gov/about-cancer/treatment/drugs/etoposidephosphate
Etoposide:cancer.gov/about-cancer/treatment/drugs/etoposide
Etoposide Phosphate:cancer.gov/about-cancer/treatment/drugs/etoposidephosphate
Everolimus:cancer.gov/about-cancer/treatment/drugs/everolimus
Evista (Raloxifene Hydrochloride):cancer.gov/about-cancer/treatment/drugs/raloxifenehydrochloride
Evomela (Melphalan Hydrochloride):cancer.gov/about-cancer/treatment/drugs/melphalan-hydrochloride
Exemestane:cancer.gov/about-cancer/treatment/drugs/exemestane
5-FU (Fluorouracil Injection):cancer.gov/about-cancer/treatment/drugs/fluorouracil
5-FU (Fluorouracil Topical):cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
Fam-Trastuzumab Deruxtecan-nxki:cancer.gov/about-cancer/treatment/drugs/famtrastuzumabderuxtecan-nxki
Fareston (Toremifene):cancer.gov/about-cancer/treatment/drugs/toremifene
Faslodex (Fulvestrant):cancer.gov/about-cancer/treatment/drugs/fulvestrant
FEC:cancer.gov/about-cancer/treatment/drugs/fec
Fedratinib Hydrochloride:cancer.gov/about-cancer/treatment/drugs/fedratinibhydrochloride
Femara (Letrozole):cancer.gov/about-cancer/treatment/drugs/letrozole
Filgrastim:cancer.gov/about-cancer/treatment/drugs/filgrastim
Firmagon (Degarelix):cancer.gov/about-cancer/treatment/drugs/degarelix
Fludarabine Phosphate:cancer.gov/about-cancer/treatment/drugs/fludarabinephosphate
Fluoroplex (Fluorouracil Topical):cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
Fluorouracil Injection:cancer.gov/about-cancer/treatment/drugs/fluorouracil
Fluorouracil Topical:cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
Flutamide:cancer.gov/about-cancer/treatment/drugs/flutamide
FOLFIRI:cancer.gov/about-cancer/treatment/drugs/folfiri
FOLFIRI-BEVACIZUMAB:cancer.gov/about-cancer/treatment/drugs/folfiri-bevacizumab
FOLFIRI-CETUXIMAB:cancer.gov/about-cancer/treatment/drugs/folfiri-cetuximab
FOLFIRINOX:cancer.gov/about-cancer/treatment/drugs/folfirinox
FOLFOX:cancer.gov/about-cancer/treatment/drugs/folfox
Folotyn (Pralatrexate):cancer.gov/about-cancer/treatment/drugs/pralatrexate
Fostamatinib Disodium:cancer.gov/about-cancer/treatment/drugs/fostamatinibdisodium
Fotivda (Tivozanib Hydrochloride):cancer.gov/about-cancer/treatment/drugs/tivozanibhydrochloride
Fruquintinib:cancer.gov/about-cancer/treatment/drugs/fruquintinib
Fruzaqla (Fruquintinib):cancer.gov/about-cancer/treatment/drugs/fruquintinib
Fulphila (Pegfilgrastim):cancer.gov/about-cancer/treatment/drugs/pegfilgrastim
FU-LV:cancer.gov/about-cancer/treatment/drugs/fu-lv
Fulvestrant:cancer.gov/about-cancer/treatment/drugs/fulvestrant
Futibatinib:cancer.gov/about-cancer/treatment/drugs/futibatinib
Fyarro (Sirolimus Protein-Bound Particles):cancer.gov/about-cancer/treatment/drugs/sirolimus-protein-bound-particles
Gamifant (Emapalumab-lzsg):cancer.gov/about-cancer/treatment/drugs/emapalumab-lzsg
Gardasil (Recombinant HPV Quadrivalent Vaccine):cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-quadrivalent-vaccine
Gardasil 9 (Recombinant HPV Nonavalent Vaccine):cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-nonavalent-vaccine
Gavreto (Pralsetinib):cancer.gov/about-cancer/treatment/drugs/pralsetinib
Gazyva (Obinutuzumab):cancer.gov/about-cancer/treatment/drugs/obinutuzumab
Gefitinib:cancer.gov/about-cancer/treatment/drugs/gefitinib
Gemcitabine Hydrochloride:cancer.gov/about-cancer/treatment/drugs/gemcitabinehydrochloride
GEMCITABINE-CISPLATIN:cancer.gov/about-cancer/treatment/drugs/gemcitabine-cisplatin
GEMCITABINE-OXALIPLATIN:cancer.gov/about-cancer/treatment/drugs/gemcitabine-oxaliplatin
Gemtuzumab Ozogamicin:cancer.gov/about-cancer/treatment/drugs/gemtuzumabozogamicin

# For each link from above, extract Drug_name, FDA_approved, Tumor_types, Details of Condition for which FDA approved, NCI Drug dictionary definition link.

In [6]:
DEBUG = False
def extract_drugname_cancerlist_nci_link(link):
    #print(links)
    url='https://www.'+link.replace(' ', '-')
    #url=links
    print(url)
    page = urlopen(url)
    #print(page)
    soup = bs(page)

    article = soup.find('article')
    #print(article)
    #Drug name in h1 tag
    drug=article.find('h1').text

    #FDA approved or not 
    fda_app = ""
    fda_sec = article.find_all('div', class_='two-columns brand-fda')
    if fda_sec :
        if DEBUG : print('FDA section found')
        for sec in fda_sec:
            if DEBUG : 
                print('\t',sec.text)
                print('\t',sec.find('div', class_='column1'))
            if 'FDA' in sec.find('div', class_='column1').text:
                if DEBUG : print('\tFOUND FDA')
                fda_app = sec.find('div',class_='column2').text
    
    #Get drug usage details now
    #print('##################################')
    paras = article.find("div",class_='accordion')
    #Variable is set to true if details found in the page
    found = False
    drug_details = ""
    nci_ddd_link=""
    ct_link=""
    cancer_list=[]
    for p in paras.findChildren(recursive=False):
        if DEBUG :
            print('----')
            print(p)
        #Need to capture data between heading "Use in Cancer" and "More About"
        #Discard capturing the other data
        if found and "more about" in p.text.lower():
            #print(':::::::::::',p)
            found = False
            if DEBUG : print('---End of drug details')
        #NCI link
        if not found and "nci drug dictionary" in p.text.lower():
            #print('$$$$$$$$$$$$$$$ Link ::: ',p)
            nci_ddd_link= p.find('a')['href']
            #print(nci_site)
            #break
        elif not found and "find clinical trials" in p.text.lower():
            #print('--------Clinical trials-----')
            #print(p.find('a')['href'])
            ct_link = p.find('a')['href']
            break
        if found :
            if DEBUG : 
                print(p.name)
                print(p.text)
            if p.name != 'a' and p.name !='strong':
                if p.findChildren() and p.name != 'p':
                    if DEBUG : print('******In find children******')
                    for x in p.findChildren():
                        if DEBUG : 
                            print('\t',x.name)
                            print('\t',x.text)
                        if x.name != 'a' and x.name !='strong':
                            #Remove extra spaces in the text and then append
                            txt = ' '.join(x.text.replace('\n', ' ').replace('\r', ' ').split())
                            drug_details += "\n" + txt
                            #print('\t',x.text)
                            #print('\t',x.name)
                        elif x.name == 'strong':
                            #All disease mentions are bold with strong tag
                            cancer_list.append(x.text)
                else:
                    if DEBUG : print('******In else of find children******')
                    
                    #Remove extra spaces in the text and then append
                    txt = ' '.join(p.text.replace('\n', ' ').replace('\r', ' ').split())
                    drug_details += "\n" + txt
                    #print(p.text)
                    #print(p.name)
            #This else not necessary. need to check
            elif p.name == 'strong':
                #All disease mentions are bold with strong tag
                cancer_list.append(p.text)
        elif "use in cancer" in p.text.lower():
            #set the flag to true as page has drrug usage details
            found = True
            if DEBUG : print('---Found drug details')
    if DEBUG :
        print('-------------------------------------------')
        print(fda_app,'\n',drug,'\n',cancer_list,'\n',drug_details)
        print('-------------------------------------------')
    return drug.strip(), fda_app.strip(), cancer_list, drug_details.strip(), nci_ddd_link.strip(),ct_link.strip()

In [7]:
links_list = pd.read_excel('cancer_gov_drug_list.xlsx', usecols=['Link'])
drug_info_df = pd.DataFrame(columns=['Drug_name', 'Link', 'FDA_approved', 'Tumor_types', 'Details_of_Condition_for_which_FDA_approved', 'NCI_Drug_Dictionary_Definition_link','Clinical_trials_link'])

for link in links_list['Link']:
    drug, fda_app, cancer_list, drug_details, nci_ddd_link, ct_link = extract_drugname_cancerlist_nci_link(link)
    drug_details = drug_details.replace("'", "").replace(",", " ")
    #fda_app = str(fda_app)[2:-2]
    clist = str(cancer_list)[2:-2].replace("'", "").replace(".", "")
    drug_info_df.loc[len(drug_info_df)] = {'Drug_name': drug, 'Link': link, 'FDA_approved': fda_app, 'Tumor_types': clist, 
                                           'Details_of_Condition_for_which_FDA_approved': drug_details, 
                                           'NCI_Drug_Dictionary_Definition_link': nci_ddd_link, 'Clinical_trials_link':ct_link}

#display(drug_info_df)
drug_info_df.to_excel('NCI_drug_tumor_list.xlsx', index=False)
print('NCI_drug_tumor_list Saved')

https://www.cancer.gov/about-cancer/treatment/drugs/idecabtagenevicleucel
https://www.cancer.gov/about-cancer/treatment/drugs/abemaciclib
https://www.cancer.gov/about-cancer/treatment/drugs/abirateroneacetate
https://www.cancer.gov/about-cancer/treatment/drugs/nanoparticlepaclitaxel
https://www.cancer.gov/about-cancer/treatment/drugs/abvd
https://www.cancer.gov/about-cancer/treatment/drugs/abve
https://www.cancer.gov/about-cancer/treatment/drugs/abve-pc
https://www.cancer.gov/about-cancer/treatment/drugs/ac
https://www.cancer.gov/about-cancer/treatment/drugs/acalabrutinib
https://www.cancer.gov/about-cancer/treatment/drugs/ac-t
https://www.cancer.gov/about-cancer/treatment/drugs/tocilizumab
https://www.cancer.gov/about-cancer/treatment/drugs/adagrasib
https://www.cancer.gov/about-cancer/treatment/drugs/brentuximabvedotin
https://www.cancer.gov/about-cancer/treatment/drugs/ade
https://www.cancer.gov/about-cancer/treatment/drugs/ado-trastuzumab-emtansine
https://www.cancer.gov/about-cancer/treatment/drugs/doxorubicinhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/nadofaragene-firadenovec-vncg
https://www.cancer.gov/about-cancer/treatment/drugs/afatinibdimaleate
https://www.cancer.gov/about-cancer/treatment/drugs/everolimus
https://www.cancer.gov/about-cancer/treatment/drugs/niraparib-tosylate-monohydrate-and-abiraterone-acetate
https://www.cancer.gov/about-cancer/treatment/drugs/netupitant-palonosetronhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/imiquimod
https://www.cancer.gov/about-cancer/treatment/drugs/aldesleukin
https://www.cancer.gov/about-cancer/treatment/drugs/alectinib
https://www.cancer.gov/about-cancer/treatment/drugs/alectinib
https://www.cancer.gov/about-cancer/treatment/drugs/alemtuzumab
https://www.cancer.gov/about-cancer/treatment/drugs/pemetrexeddisodium
https://www.cancer.gov/about-cancer/treatment/drugs/melphalan-hydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/melphalan
https://www.cancer.gov/about-cancer/treatment/drugs/palonosetronhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/alpelisib
https://www.cancer.gov/about-cancer/treatment/drugs/brigatinib
https://www.cancer.gov/about-cancer/treatment/drugs/bevacizumab
https://www.cancer.gov/about-cancer/treatment/drugs/aminolevulinicacid
https://www.cancer.gov/about-cancer/treatment/drugs/amifostine
https://www.cancer.gov/about-cancer/treatment/drugs/aminolevulinicacid
https://www.cancer.gov/about-cancer/treatment/drugs/amivantamab-vmjw
https://www.cancer.gov/about-cancer/treatment/drugs/anastrozole
https://www.cancer.gov/about-cancer/treatment/drugs/apalutamide
https://www.cancer.gov/about-cancer/treatment/drugs/aprepitant
https://www.cancer.gov/about-cancer/treatment/drugs/darbepoetinalfa
https://www.cancer.gov/about-cancer/treatment/drugs/pamidronatedisodium
https://www.cancer.gov/about-cancer/treatment/drugs/anastrozole
https://www.cancer.gov/about-cancer/treatment/drugs/exemestane
https://www.cancer.gov/about-cancer/treatment/drugs/nelarabine
https://www.cancer.gov/about-cancer/treatment/drugs/arsenictrioxide
https://www.cancer.gov/about-cancer/treatment/drugs/ofatumumab
https://www.cancer.gov/about-cancer/treatment/drugs/asciminib-hydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/asparaginase-erwinia-chrysanthemi
https://www.cancer.gov/about-cancer/treatment/drugs/asparaginase-erwinia-chrysanthemi-recombinant
https://www.cancer.gov/about-cancer/treatment/drugs/calaspargasepegol-mknl
https://www.cancer.gov/about-cancer/treatment/drugs/atezolizumab
https://www.cancer.gov/about-cancer/treatment/drugs/repotrectinib
https://www.cancer.gov/about-cancer/treatment/drugs/avapritinib
https://www.cancer.gov/about-cancer/treatment/drugs/bevacizumab
https://www.cancer.gov/about-cancer/treatment/drugs/avelumab
https://www.cancer.gov/about-cancer/treatment/drugs/axicabtageneciloleucel
https://www.cancer.gov/about-cancer/treatment/drugs/axitinib
https://www.cancer.gov/about-cancer/treatment/drugs/avapritinib
https://www.cancer.gov/about-cancer/treatment/drugs/azacitidine
https://www.cancer.gov/about-cancer/treatment/drugs/iobenguanei131
https://www.cancer.gov/about-cancer/treatment/drugs/erdafitinib
https://www.cancer.gov/about-cancer/treatment/drugs/avelumab
https://www.cancer.gov/about-cancer/treatment/drugs/beacopp
https://www.cancer.gov/about-cancer/treatment/drugs/belinostat
https://www.cancer.gov/about-cancer/treatment/drugs/belinostat
https://www.cancer.gov/about-cancer/treatment/drugs/belzutifan
https://www.cancer.gov/about-cancer/treatment/drugs/bendamustinehydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/bendamustinehydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/bep
https://www.cancer.gov/about-cancer/treatment/drugs/inotuzumabozogamicin
https://www.cancer.gov/about-cancer/treatment/drugs/ropeginterferon-alfa-2b-njft
https://www.cancer.gov/about-cancer/treatment/drugs/bevacizumab
https://www.cancer.gov/about-cancer/treatment/drugs/bexarotene
https://www.cancer.gov/about-cancer/treatment/drugs/bicalutamide
https://www.cancer.gov/about-cancer/treatment/drugs/carmustine
https://www.cancer.gov/about-cancer/treatment/drugs/binimetinib
https://www.cancer.gov/about-cancer/treatment/drugs/bleomycin
https://www.cancer.gov/about-cancer/treatment/drugs/blinatumomab
https://www.cancer.gov/about-cancer/treatment/drugs/blinatumomab
https://www.cancer.gov/about-cancer/treatment/drugs/bortezomib
https://www.cancer.gov/about-cancer/treatment/drugs/bosutinib
https://www.cancer.gov/about-cancer/treatment/drugs/bosutinib
https://www.cancer.gov/about-cancer/treatment/drugs/encorafenib
https://www.cancer.gov/about-cancer/treatment/drugs/brentuximabvedotin
https://www.cancer.gov/about-cancer/treatment/drugs/brexucabtageneautoleucel
https://www.cancer.gov/about-cancer/treatment/drugs/lisocabtagenemaraleucel
https://www.cancer.gov/about-cancer/treatment/drugs/brigatinib
https://www.cancer.gov/about-cancer/treatment/drugs/zanubrutinib
https://www.cancer.gov/about-cancer/treatment/drugs/bumel
https://www.cancer.gov/about-cancer/treatment/drugs/busulfan
https://www.cancer.gov/about-cancer/treatment/drugs/busulfan
https://www.cancer.gov/about-cancer/treatment/drugs/cabazitaxel
https://www.cancer.gov/about-cancer/treatment/drugs/caplacizumab-yhdp
https://www.cancer.gov/about-cancer/treatment/drugs/cabozantinib-s-malate
https://www.cancer.gov/about-cancer/treatment/drugs/cabozantinib-s-malate
https://www.cancer.gov/about-cancer/treatment/drugs/caf
https://www.cancer.gov/about-cancer/treatment/drugs/calaspargasepegol-mknl
https://www.cancer.gov/about-cancer/treatment/drugs/acalabrutinib
https://www.cancer.gov/about-cancer/treatment/drugs/alemtuzumab
https://www.cancer.gov/about-cancer/treatment/drugs/irinotecanhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/capecitabine
https://www.cancer.gov/about-cancer/treatment/drugs/capivasertib
https://www.cancer.gov/about-cancer/treatment/drugs/caplacizumab-yhdp
https://www.cancer.gov/about-cancer/treatment/drugs/capmatinibhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/capox
https://www.cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
https://www.cancer.gov/about-cancer/treatment/drugs/carboplatin
https://www.cancer.gov/about-cancer/treatment/drugs/carboplatin-taxol
https://www.cancer.gov/about-cancer/treatment/drugs/carfilzomib
https://www.cancer.gov/about-cancer/treatment/drugs/carmustine
https://www.cancer.gov/about-cancer/treatment/drugs/carmustineimplant
https://www.cancer.gov/about-cancer/treatment/drugs/ciltacabtagene-autoleucel
https://www.cancer.gov/about-cancer/treatment/drugs/bicalutamide
https://www.cancer.gov/about-cancer/treatment/drugs/cem
https://www.cancer.gov/about-cancer/treatment/drugs/cemiplimab-rwlc
https://www.cancer.gov/about-cancer/treatment/drugs/ceritinib
https://www.cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-bivalent-vaccine
https://www.cancer.gov/about-cancer/treatment/drugs/cetuximab
https://www.cancer.gov/about-cancer/treatment/drugs/cev
https://www.cancer.gov/about-cancer/treatment/drugs/chlorambucil
https://www.cancer.gov/about-cancer/treatment/drugs/chlorambucil-prednisone
https://www.cancer.gov/about-cancer/treatment/drugs/chop
https://www.cancer.gov/about-cancer/treatment/drugs/ciltacabtagene-autoleucel
https://www.cancer.gov/about-cancer/treatment/drugs/cisplatin
https://www.cancer.gov/about-cancer/treatment/drugs/cladribine
https://www.cancer.gov/about-cancer/treatment/drugs/clofarabine
https://www.cancer.gov/about-cancer/treatment/drugs/clofarabine
https://www.cancer.gov/about-cancer/treatment/drugs/cmf
https://www.cancer.gov/about-cancer/treatment/drugs/cobimetinib
https://www.cancer.gov/about-cancer/treatment/drugs/glofitamab-gxbm
https://www.cancer.gov/about-cancer/treatment/drugs/cabozantinib-s-malate
https://www.cancer.gov/about-cancer/treatment/drugs/copdac
https://www.cancer.gov/about-cancer/treatment/drugs/duvelisib
https://www.cancer.gov/about-cancer/treatment/drugs/copp
https://www.cancer.gov/about-cancer/treatment/drugs/copp-abv
https://www.cancer.gov/about-cancer/treatment/drugs/dactinomycin
https://www.cancer.gov/about-cancer/treatment/drugs/cobimetinib
https://www.cancer.gov/about-cancer/treatment/drugs/crizotinib
https://www.cancer.gov/about-cancer/treatment/drugs/cvp
https://www.cancer.gov/about-cancer/treatment/drugs/cyclophosphamide
https://www.cancer.gov/about-cancer/treatment/drugs/ramucirumab
https://www.cancer.gov/about-cancer/treatment/drugs/cytarabine
https://www.cancer.gov/about-cancer/treatment/drugs/dabrafenib
https://www.cancer.gov/about-cancer/treatment/drugs/dacarbazine
https://www.cancer.gov/about-cancer/treatment/drugs/decitabine
https://www.cancer.gov/about-cancer/treatment/drugs/dacomitinib
https://www.cancer.gov/about-cancer/treatment/drugs/dactinomycin
https://www.cancer.gov/about-cancer/treatment/drugs/naxitamab-gqgk
https://www.cancer.gov/about-cancer/treatment/drugs/daratumumab
https://www.cancer.gov/about-cancer/treatment/drugs/daratumumabandhyaluronidase-fihj
https://www.cancer.gov/about-cancer/treatment/drugs/darbepoetinalfa
https://www.cancer.gov/about-cancer/treatment/drugs/darolutamide
https://www.cancer.gov/about-cancer/treatment/drugs/daratumumab
https://www.cancer.gov/about-cancer/treatment/drugs/daratumumabandhyaluronidase-fihj
https://www.cancer.gov/about-cancer/treatment/drugs/dasatinib
https://www.cancer.gov/about-cancer/treatment/drugs/daunorubicinhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/daunorubicinhydrochlorideandcytarabineliposome
https://www.cancer.gov/about-cancer/treatment/drugs/glasdegibmaleate
https://www.cancer.gov/about-cancer/treatment/drugs/decitabine
https://www.cancer.gov/about-cancer/treatment/drugs/decitabineandcedazuridine
https://www.cancer.gov/about-cancer/treatment/drugs/defibrotide-sodium
https://www.cancer.gov/about-cancer/treatment/drugs/defibrotide-sodium
https://www.cancer.gov/about-cancer/treatment/drugs/degarelix
https://www.cancer.gov/about-cancer/treatment/drugs/denileukindiftitox
https://www.cancer.gov/about-cancer/treatment/drugs/denosumab
https://www.cancer.gov/about-cancer/treatment/drugs/dexamethasone
https://www.cancer.gov/about-cancer/treatment/drugs/dexrazoxanehydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/dinutuximab
https://www.cancer.gov/about-cancer/treatment/drugs/docetaxel
https://www.cancer.gov/about-cancer/treatment/drugs/dostarlimab-gxly
https://www.cancer.gov/about-cancer/treatment/drugs/doxorubicin-hydrochloride-liposome
https://www.cancer.gov/about-cancer/treatment/drugs/doxorubicinhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/doxorubicin-hydrochloride-liposome
https://www.cancer.gov/about-cancer/treatment/drugs/durvalumab
https://www.cancer.gov/about-cancer/treatment/drugs/duvelisib
https://www.cancer.gov/about-cancer/treatment/drugs/eflornithine-hydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
https://www.cancer.gov/about-cancer/treatment/drugs/elacestrant-dihydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/mirvetuximab-soravtansine-gynx
https://www.cancer.gov/about-cancer/treatment/drugs/leuprolideacetate
https://www.cancer.gov/about-cancer/treatment/drugs/rasburicase
https://www.cancer.gov/about-cancer/treatment/drugs/epirubicinhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/elotuzumab
https://www.cancer.gov/about-cancer/treatment/drugs/oxaliplatin
https://www.cancer.gov/about-cancer/treatment/drugs/elranatamab-bcmm
https://www.cancer.gov/about-cancer/treatment/drugs/elranatamab-bcmm
https://www.cancer.gov/about-cancer/treatment/drugs/eltrombopagolamine
https://www.cancer.gov/about-cancer/treatment/drugs/tagraxofusp-erzs
https://www.cancer.gov/about-cancer/treatment/drugs/emapalumab-lzsg
https://www.cancer.gov/about-cancer/treatment/drugs/aprepitant
https://www.cancer.gov/about-cancer/treatment/drugs/elotuzumab
https://www.cancer.gov/about-cancer/treatment/drugs/enasidenibmesylate
https://www.cancer.gov/about-cancer/treatment/drugs/encorafenib
https://www.cancer.gov/about-cancer/treatment/drugs/enfortumabvedotin-ejfv
https://www.cancer.gov/about-cancer/treatment/drugs/famtrastuzumabderuxtecan-nxki
https://www.cancer.gov/about-cancer/treatment/drugs/entrectinib
https://www.cancer.gov/about-cancer/treatment/drugs/enzalutamide
https://www.cancer.gov/about-cancer/treatment/drugs/epcoritamab-bysp
https://www.cancer.gov/about-cancer/treatment/drugs/epirubicinhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/epcoritamab-bysp
https://www.cancer.gov/about-cancer/treatment/drugs/epoch
https://www.cancer.gov/about-cancer/treatment/drugs/epoetinalfa
https://www.cancer.gov/about-cancer/treatment/drugs/epoetinalfa
https://www.cancer.gov/about-cancer/treatment/drugs/cetuximab
https://www.cancer.gov/about-cancer/treatment/drugs/erdafitinib
https://www.cancer.gov/about-cancer/treatment/drugs/eribulinmesylate
https://www.cancer.gov/about-cancer/treatment/drugs/vismodegib
https://www.cancer.gov/about-cancer/treatment/drugs/apalutamide
https://www.cancer.gov/about-cancer/treatment/drugs/erlotinibhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/asparaginase-erwinia-chrysanthemi
https://www.cancer.gov/about-cancer/treatment/drugs/amifostine
https://www.cancer.gov/about-cancer/treatment/drugs/etoposidephosphate
https://www.cancer.gov/about-cancer/treatment/drugs/etoposide
https://www.cancer.gov/about-cancer/treatment/drugs/etoposidephosphate
https://www.cancer.gov/about-cancer/treatment/drugs/everolimus
https://www.cancer.gov/about-cancer/treatment/drugs/raloxifenehydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/melphalan-hydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/exemestane
https://www.cancer.gov/about-cancer/treatment/drugs/fluorouracil
https://www.cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
https://www.cancer.gov/about-cancer/treatment/drugs/famtrastuzumabderuxtecan-nxki
https://www.cancer.gov/about-cancer/treatment/drugs/toremifene
https://www.cancer.gov/about-cancer/treatment/drugs/fulvestrant
https://www.cancer.gov/about-cancer/treatment/drugs/fec
https://www.cancer.gov/about-cancer/treatment/drugs/fedratinibhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/letrozole
https://www.cancer.gov/about-cancer/treatment/drugs/filgrastim
https://www.cancer.gov/about-cancer/treatment/drugs/degarelix
https://www.cancer.gov/about-cancer/treatment/drugs/fludarabinephosphate
https://www.cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
https://www.cancer.gov/about-cancer/treatment/drugs/fluorouracil
https://www.cancer.gov/about-cancer/treatment/drugs/fluorouracil-topical
https://www.cancer.gov/about-cancer/treatment/drugs/flutamide
https://www.cancer.gov/about-cancer/treatment/drugs/folfiri
https://www.cancer.gov/about-cancer/treatment/drugs/folfiri-bevacizumab
https://www.cancer.gov/about-cancer/treatment/drugs/folfiri-cetuximab
https://www.cancer.gov/about-cancer/treatment/drugs/folfirinox
https://www.cancer.gov/about-cancer/treatment/drugs/folfox
https://www.cancer.gov/about-cancer/treatment/drugs/pralatrexate
https://www.cancer.gov/about-cancer/treatment/drugs/fostamatinibdisodium
https://www.cancer.gov/about-cancer/treatment/drugs/tivozanibhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/fruquintinib
https://www.cancer.gov/about-cancer/treatment/drugs/fruquintinib
https://www.cancer.gov/about-cancer/treatment/drugs/pegfilgrastim
https://www.cancer.gov/about-cancer/treatment/drugs/fu-lv
https://www.cancer.gov/about-cancer/treatment/drugs/fulvestrant
https://www.cancer.gov/about-cancer/treatment/drugs/futibatinib
https://www.cancer.gov/about-cancer/treatment/drugs/sirolimus-protein-bound-particles
https://www.cancer.gov/about-cancer/treatment/drugs/emapalumab-lzsg
https://www.cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-quadrivalent-vaccine
https://www.cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-nonavalent-vaccine
https://www.cancer.gov/about-cancer/treatment/drugs/pralsetinib
https://www.cancer.gov/about-cancer/treatment/drugs/obinutuzumab
https://www.cancer.gov/about-cancer/treatment/drugs/gefitinib
https://www.cancer.gov/about-cancer/treatment/drugs/gemcitabinehydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/gemcitabine-cisplatin
https://www.cancer.gov/about-cancer/treatment/drugs/gemcitabine-oxaliplatin
https://www.cancer.gov/about-cancer/treatment/drugs/gemtuzumabozogamicin
https://www.cancer.gov/about-cancer/treatment/drugs/gemcitabinehydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/afatinibdimaleate
https://www.cancer.gov/about-cancer/treatment/drugs/gilteritinibfumarate
https://www.cancer.gov/about-cancer/treatment/drugs/glasdegibmaleate
https://www.cancer.gov/about-cancer/treatment/drugs/imatinibmesylate
https://www.cancer.gov/about-cancer/treatment/drugs/carmustineimplant
https://www.cancer.gov/about-cancer/treatment/drugs/glofitamab-gxbm
https://www.cancer.gov/about-cancer/treatment/drugs/glucarpidase
https://www.cancer.gov/about-cancer/treatment/drugs/goserelinacetate
https://www.cancer.gov/about-cancer/treatment/drugs/granisetron
https://www.cancer.gov/about-cancer/treatment/drugs/granisetronhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/filgrastim
https://www.cancer.gov/about-cancer/treatment/drugs/eribulinmesylate
https://www.cancer.gov/about-cancer/treatment/drugs/propranolol-hydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/melphalan-hydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/trastuzumabandhyaluronidase-oysk
https://www.cancer.gov/about-cancer/treatment/drugs/trastuzumab
https://www.cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-bivalent-vaccine
https://www.cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-nonavalent-vaccine
https://www.cancer.gov/about-cancer/treatment/drugs/recombinant-hpv-quadrivalent-vaccine
https://www.cancer.gov/about-cancer/treatment/drugs/topotecanhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/hydroxyurea
https://www.cancer.gov/about-cancer/treatment/drugs/hydroxyurea
https://www.cancer.gov/about-cancer/treatment/drugs/hyper-cvad
https://www.cancer.gov/about-cancer/treatment/drugs/palbociclib
https://www.cancer.gov/about-cancer/treatment/drugs/ibritumomabtiuxetan
https://www.cancer.gov/about-cancer/treatment/drugs/ibrutinib
https://www.cancer.gov/about-cancer/treatment/drugs/ice
https://www.cancer.gov/about-cancer/treatment/drugs/ponatinibhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/idarubicinhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/idarubicinhydrochloride
https://www.cancer.gov/about-cancer/treatment/drugs/idecabtagenevicleucel
https://www.cancer.gov/about-cancer/treatment/drugs/idelalisib

In [8]:
def getNCI_Thesaurus_Link(driver,url):
    print(url)
    driver.get(url)
    time.sleep(1)
    soup = bs(driver.page_source)
    #print(bs)
    nci_link = soup.find('a',class_="dictionary-definiton__nci-thesaurus-link")
    if nci_link:
        print(nci_link['href'])
        #print(df)
        return nci_link['href']
    else:
        return ""
        
def populateNCI_Thesaurus_Link():
    options = Options()
    options.add_argument('--disable-application-cache')
    options.add_argument('--headless')
    options.add_argument("--no-sandbox")
    options.add_argument("--window-size=1920,1080")
    
    service = Service()
    driver = webdriver.Chrome(service=service, options=options)

    df = pd.read_excel('NCI_drug_tumor_list.xlsx')
    df = df.fillna("")
    for i, row in df.iterrows():
        print('--------------------------')
        nci_def_link = row['NCI_Drug_Dictionary_Definition_link']
        #print(nci_def_link)
        nci_link = getNCI_Thesaurus_Link(driver,nci_def_link)
        df.at[i,'NCI_Thesaurus_Link'] = nci_link
    display(df)
    df.to_excel('NCI_drug_tumor_list_Thesaurus_link.xlsx', index=False)
    print('NCI_drug_tumor_list_Thesaurus_link Saved after populating Thesaurus link')
populateNCI_Thesaurus_Link()

--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/763837
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C117729
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/706364
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C97660
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/552704
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C68845
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/38690
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2688
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/39364
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9509
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/657148
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C67162
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/683768
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C67175
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/656900
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C63415
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/756623
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C113442
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/631444
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C63427
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/713832
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C84217
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/796791
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C157493
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/530758
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C66944
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/656988
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9579
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/564399
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C82492
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/38860
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1326
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/573538
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C71011
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/537572
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C97273
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/372905
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48387
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/811466
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C191876
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/771103
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C121569
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/38558
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1431
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/39756
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1498
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/733572
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C101790
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/733572
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C101790
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/37783
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1681
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/42328
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1533
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/42973
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48002
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/779085
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C633
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/486366
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C47650
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/687431
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C94214
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/714373
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C98831
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/43234
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2039
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/42648
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1849
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/39741
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C488
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/42648
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1849
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/777269
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C124993
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/42540
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1607
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/683082
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C92574
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/454517
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C49173
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/38676
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1878
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/39149
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1345
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/42540
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1607
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/42297
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1097
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/43260
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1704
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/43067
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1005
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/530015
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C66952
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/758893
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C171722
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/601044
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C64260
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/800241
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C167120
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/595298
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C78198
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/702758
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C106250
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/788549
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C133821
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/775630
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C123827
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/43234
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2039
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/745752
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C116870
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/768723
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C120309
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/352181
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C38718
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/775630
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C123827
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/39153
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C288
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/38020
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C970
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/741845
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C103273
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/745752
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C116870
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/631451
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C11638
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/454583
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48812
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/454583
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48812
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/788947
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C135627
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/350251
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C61565
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/350251
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C61565
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/656990
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C63488
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/352004
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C71542
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/753252
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C111892
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/43234
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2039
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/42117
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1635
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/41298
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1599
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/43027
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C349
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/653635
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C84865
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/39139
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C312
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/487684
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C62528
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/487684
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C62528
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/43560
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1851
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/467222
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C60809
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/467222
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C60809
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/712549
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C98283
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/530758
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C66944
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/802259
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C170439
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/778386
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C125192
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/714373
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C98831
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/768510
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C141428
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/780869
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C126792
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/41947
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C321
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/41947
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C321
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/534131
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C66937
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/782660
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C128625
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/461103
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C97938
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/461103
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C97938
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/40973
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9533
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/595298
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C78198
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/756623
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C113442
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/37783
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1681
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/41714
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1381
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/42852
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1794
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/688304
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C102564
--------------------------
https://www.cancer.gov/publications/dictionaries/cancer-drug/def/782660

,Drug_name,Link,FDA_approved,Tumor_types,Details_of_Condition_for_which_FDA_approved,NCI_Drug_Dictionary_Definition_link,Clinical_trials_link,NCI_Thesaurus_Link
0,Idecabtagene Vicleucel,cancer.gov/about-cancer/treatment/drugs/idecab...,Yes,Multiple myeloma,Idecabtagene vicleucel is approved to treat:\n...,https://www.cancer.gov/publications/dictionari...,https://www.cancer.gov/research/participate/cl...,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...
1,Abemaciclib,cancer.gov/about-cancer/treatment/drugs/abemac...,Yes,Breast cancer,Abemaciclib is approved to treat:\nBreast canc...,https://www.cancer.gov/publications/dictionari...,https://www.cancer.gov/research/participate/cl...,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...
2,Abiraterone Acetate,cancer.gov/about-cancer/treatment/drugs/abirat...,Yes,Prostate cancer,Abiraterone acetate is approved to be used wit...,https://www.cancer.gov/publications/dictionari...,https://www.cancer.gov/research/participate/cl...,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...
3,Paclitaxel Albumin-stabilized Nanoparticle For...,cancer.gov/about-cancer/treatment/drugs/nanopa...,Yes,"Breast cancer, Non-small cell lung cancer, Pan...",Paclitaxel albumin-stabilized nanoparticle for...,https://www.cancer.gov/publications/dictionari...,https://www.cancer.gov/research/participate/cl...,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...
4,ABVD,cancer.gov/about-cancer/treatment/drugs/abvd,,Hodgkin lymphoma,ABVD is used to treat:\nHodgkin lymphoma.\nThi...,https://www.cancer.gov/publications/dictionari...,,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...
...,...,...,...,...,...,...,...,...
691,Idelalisib,cancer.gov/about-cancer/treatment/drugs/idelal...,Yes,Chronic lymphocytic leukemia,Idelalisib is approved to treat:\nChronic lymp...,https://www.cancer.gov/publications/dictionari...,https://www.cancer.gov/research/participate/cl...,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...
692,Ceritinib,cancer.gov/about-cancer/treatment/drugs/ceritinib,Yes,Non-small cell lung cancer,Ceritinib is approved to treat:\nNon-small cel...,https://www.cancer.gov/publications/dictionari...,https://www.cancer.gov/research/participate/cl...,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...
693,Loncastuximab Tesirine-lpyl,cancer.gov/about-cancer/treatment/drugs/loncas...,Yes,B-cell non-Hodgkin lymphoma,Loncastuximab tesirine-lpyl is approved to tre...,https://www.cancer.gov/publications/dictionari...,https://www.cancer.gov/research/participate/cl...,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...
694,Retifanlimab-dlwr,cancer.gov/about-cancer/treatment/drugs/retifa...,Yes,Merkel cell carcinoma,Retifanlimab-dlwr is approved to treat adults ...,https://www.cancer.gov/publications/dictionari...,https://www.cancer.gov/research/participate/cl...,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...
695,Abiraterone Acetate,cancer.gov/about-cancer/treatment/drugs/abirat...,Yes,Prostate cancer,Abiraterone acetate is approved to be used wit...,https://www.cancer.gov/publications/dictionari...,https://www.cancer.gov/research/participate/cl...,https://ncit.nci.nih.gov/ncitbrowser/ConceptRe...

NCI_drug_tumor_list_Thesaurus_link Saved after populating Thesaurus link

# Extract Definition,Synonyms, Extranal source code from NCI Thesaurus

In [23]:
def populate_NCI_Thesaurus_Details():
    df = pd.read_excel('NCI_drug_tumor_list_Thesaurus_link.xlsx')
    df = df.fillna("")
    for i, row in df.iterrows():
        print('--------------------------')
        url = row['NCI_Thesaurus_Link']
        print(url)
        if url != '':
            page = requests.get(url)
            soup = bs(page.content, "html.parser")
            
            item_list = soup.find_all('p')
            for item in item_list: 
                text = item.text
                #print(text)
                if 'NCI Thesaurus Code' in text:
                    df.at[i,'NCI_Thesaurus_Code'] = text.split(":")[1].strip()
                elif 'Preferred Name' in text: 
                    #print('Preferred Name' in text)
                    df.at[i,'NCI_Preferred_Name'] =text.split(":")[1].strip()
                elif 'Display Name' in text: 
                    #print('Display Name' in text)
                    df.at[i,'NCI_Display_Name'] = text.split(":")[1].strip()
                elif 'Synonyms & Abbreviations' in text:
                    slist = item.find_all('td')
                    synonyms = ""
                    for syn in slist:
                        if synonyms.strip() != '':
                            synonyms = synonyms + "||"
                        synonyms = synonyms + syn.text
                    #print('----Synonyms ::',synonyms)
                    df.at[i,'NCI_Synonyms_and_Abbreviations'] = synonyms
                elif 'Definition' in text:
                    df.at[i,'NCI_Definition'] = text.split(":")[1].strip()
                elif 'External Source Codes' in text:
                    esc = ""
                    eslist = item.find_all('tr')
                    #print('$$$$$$$$$$$$$$$$$$')
                    for es in eslist:
                        es_tds = es.find_all('td')
                        #Remove extract breaks and spaces
                        tmp = es_tds[0].text.strip() +":"+es_tds[1].text.strip()
                        txt = ' '.join(tmp.replace('\n', ' ').replace('\r', ' ').split())
                        esc = esc.strip() + "\n"+ txt
                        if 'FDA UNII Code' in es_tds[0].text :
                            df.at[i,'FDA_UNII_Code'] = es_tds[1].text.strip()
                    df.at[i,'NCI_External_Source_Codes'] = esc
                    #print(esc)
    # Write the final DataFrame to Excel
    df.to_excel('NCI_drug_tumor_list_NCI_Thesaurus_Data.xlsx', index=False)
    print('NCI_drug_tumor_list_NCI_Thesaurus_Data Saved after populating NCI Thesaurus details')

populate_NCI_Thesaurus_Details()

--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C117729
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C97660
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C68845
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2688
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9509
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C67162
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C67175
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C63415
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C113442
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C63427
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C84217
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C157493
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C66944
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9579
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C82492
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1326
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C71011
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C97273
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48387
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C191876
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C121569
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1431
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1498
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C101790
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C101790
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1681
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1533
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48002
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C633
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C47650
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C94214
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C98831
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2039
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1849
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C488
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1849
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C124993
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1607
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C92574
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C49173
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1878
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1345
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1607
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1097
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1704
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1005
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C66952
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C171722
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C64260
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C167120
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C78198
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C106250
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C133821
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C123827
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2039
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C116870
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C120309
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C38718
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C123827
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C288
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C970
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C103273
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C116870
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C11638
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48812
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48812
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C135627
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C61565
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C61565
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C63488
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C71542
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C111892
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2039
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1635
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1599
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C349
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C84865
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C312
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C62528
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C62528
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1851
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C60809
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C60809
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C98283
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C66944
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C170439
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C125192
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C98831
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C141428
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C126792
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C321
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C321
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C66937
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C128625
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C97938
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C97938
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9533
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C78198
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C113442
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1681
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1381
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1794
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C102564
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C128625
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C138995
--------------------------

--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C125194
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1282
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C63402
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C52196
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C349
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C2487
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C148498
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1599
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C125601
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C121540
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C115112
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48395
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1723
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C129579
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C362
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C63752
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9549
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C148498
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C376
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1336
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C26638
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C26638
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9874
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C68923
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C148486
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C97938
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C123278
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C99225
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9567
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C67174
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C412
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C68923
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C74061
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C9573
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C405
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C70792
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C408
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C128059
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C411
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C981
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C53398
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C412
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C123428
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C74007
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C156401
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1878
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C104748
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C74007
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C156401
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C38713
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1583
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C67504
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C156894
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C981
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C115102
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1064
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1064
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C48385
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C1476
--------------------------
https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C61313
--------------------------

# DATA FROM PUBCHEM

# The drug names in this file NCI_drug_tumor_list.xlsx is used to get SID from PubChem using esearch. It is saved in excel file SID_Drug_info.xlsx

In [13]:
def getsidandsource(drug):
    drug=drug.replace(" ","+")
    #print(drug)
    time.sleep(2)
    link = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term="+drug+"&retmode=xml"
    print(link)
    page = urllib.request.urlopen(link)
    page= page.read().decode('utf-8')
    #print(page)
    esearch_result = xmltodict.parse(page)
    #print(esearch_result)
    sid=[]
    search = esearch_result['eSearchResult']['IdList']['Id']
    search=str(search)[1:-1]
    sid.append(search)
    #print(sid)
    return sid

In [14]:
drug_name = pd.read_excel('NCI_drug_tumor_list_NCI_Thesaurus_Data.xlsx', usecols=['Drug_name'])
drug_name = drug_name['Drug_name'].unique()
drug_sid_pc_df = pd.DataFrame(columns=['Drug_name', 'SID'])

for drug in drug_name:
    try:
        sid = getsidandsource(drug)
        sid = ','.join(sid)
        drug_sid_pc_df = pd.concat([drug_sid_pc_df, pd.DataFrame({'Drug_name': [drug], 'SID': [sid]})], ignore_index=True)
    except Exception as e:
        print('Exception:', drug, e)

drug_sid_pc_df.to_excel('SID_Drug_info.xlsx', index=False)
display(drug_sid_pc_df)
print('Saved SID_Drug_Info')

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Idecabtagene+Vicleucel&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Abemaciclib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Abiraterone+Acetate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Paclitaxel+Albumin-stabilized+Nanoparticle+Formulation&retmode=xml
Exception: Paclitaxel Albumin-stabilized Nanoparticle Formulation 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=ABVD&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=ABVE&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=ABVE-PC&retmode=xml
Exception: ABVE-PC 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=AC&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Acalabrutinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=AC-T&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Tocilizumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Adagrasib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Brentuximab+Vedotin&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=ADE&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Ado-Trastuzumab+Emtansine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Doxorubicin+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Nadofaragene+Firadenovec-vncg&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Afatinib+Dimaleate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Everolimus&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Niraparib+Tosylate+Monohydrate+and+Abiraterone+Acetate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Netupitant+and+Palonosetron+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Imiquimod&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Aldesleukin&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Alectinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Alemtuzumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Pemetrexed+Disodium&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Melphalan+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Melphalan&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Palonosetron+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Alpelisib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Brigatinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Bevacizumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Aminolevulinic+Acid+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Amifostine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Amivantamab-vmjw&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Anastrozole&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Apalutamide&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Aprepitant&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Darbepoetin+Alfa&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Pamidronate+Disodium&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Exemestane&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Nelarabine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Arsenic+Trioxide&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Ofatumumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Asciminib+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Asparaginase+Erwinia+Chrysanthemi&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Asparaginase+Erwinia+Chrysanthemi+(Recombinant)-rywn&retmode=xml
Exception: Asparaginase Erwinia Chrysanthemi (Recombinant)-rywn 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Calaspargase+Pegol-mknl&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Atezolizumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Repotrectinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Avapritinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Avelumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Axicabtagene+Ciloleucel&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Axitinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Azacitidine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Iobenguane+I+131&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Erdafitinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=BEACOPP&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Belinostat&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Belzutifan&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Bendamustine+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=BEP&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Inotuzumab+Ozogamicin&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Ropeginterferon+Alfa-2b-njft&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Bexarotene&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Bicalutamide&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Carmustine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Binimetinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Bleomycin+Sulfate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Blinatumomab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Bortezomib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Bosutinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Encorafenib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Brexucabtagene+Autoleucel&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Lisocabtagene+Maraleucel&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Zanubrutinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=BuMel&retmode=xml
Exception: BuMel 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Busulfan&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Cabazitaxel&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Caplacizumab-yhdp&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Cabozantinib-S-Malate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=CAF&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Irinotecan+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Capecitabine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Capivasertib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Capmatinib+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=CAPOX&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Fluorouracil+(Topical)&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Carboplatin&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=CARBOPLATIN-TAXOL&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Carfilzomib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Carmustine+Implant&retmode=xml
Exception: Carmustine Implant 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Ciltacabtagene+Autoleucel&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=CEM&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Cemiplimab-rwlc&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Ceritinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Recombinant+Human+Papillomavirus+(HPV)+Bivalent+Vaccine&retmode=xml
Exception: Recombinant Human Papillomavirus (HPV) Bivalent Vaccine 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Cetuximab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=CEV&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Chlorambucil&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=CHLORAMBUCIL-PREDNISONE&retmode=xml
Exception: CHLORAMBUCIL-PREDNISONE 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=CHOP&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Cisplatin&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Cladribine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Clofarabine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=CMF&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Cobimetinib+Fumarate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Glofitamab-gxbm&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=COPDAC&retmode=xml
Exception: COPDAC 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Duvelisib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=COPP&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=COPP-ABV&retmode=xml
Exception: COPP-ABV 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Dactinomycin&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Crizotinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=CVP&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Cyclophosphamide&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Ramucirumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Cytarabine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Dabrafenib+Mesylate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Dacarbazine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Decitabine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Dacomitinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Naxitamab-gqgk&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Daratumumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Daratumumab+and+Hyaluronidase-fihj&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Darolutamide&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Dasatinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Daunorubicin+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Daunorubicin+Hydrochloride+and+Cytarabine+Liposome&retmode=xml
Exception: Daunorubicin Hydrochloride and Cytarabine Liposome 'NoneType' object is not subscriptable
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Glasdegib+Maleate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Decitabine+and+Cedazuridine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Defibrotide+Sodium&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Degarelix&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Denileukin+Diftitox&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Denosumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Dexamethasone&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Dexrazoxane+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Dinutuximab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Docetaxel&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Dostarlimab-gxly&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Doxorubicin+Hydrochloride+Liposome&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Durvalumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Eflornithine+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Elacestrant+Dihydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Mirvetuximab+Soravtansine-gynx&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Leuprolide+Acetate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Rasburicase&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Epirubicin+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Elotuzumab&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Oxaliplatin&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Elranatamab-bcmm&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Eltrombopag+Olamine&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Tagraxofusp-erzs&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Emapalumab-lzsg&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Enasidenib+Mesylate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Enfortumab+Vedotin-ejfv&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Fam-Trastuzumab+Deruxtecan-nxki&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Entrectinib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Enzalutamide&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Epcoritamab-bysp&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=EPOCH&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Epoetin+Alfa&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Eribulin+Mesylate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Vismodegib&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Erlotinib+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Etoposide+Phosphate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Etoposide&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Raloxifene+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Fluorouracil+Injection&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Toremifene&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Fulvestrant&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=FEC&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Fedratinib+Hydrochloride&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Letrozole&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Filgrastim&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Fludarabine+Phosphate&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=Flutamide&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pcsubstance&term=FOLFIRI&retmode=xml

                  Drug_name                                                SID
0    Idecabtagene Vicleucel  '482042220', '481101667', '472421408', '472420...
1               Abemaciclib  '489440693', '489440495', '489355322', '488985...
2       Abiraterone Acetate  '488957728', '488318359', '488305682', '488224...
3                      ABVD  '135264548', '135264424', '127830723', '537882...
4                      ABVE                                            3533476
..                      ...                                                ...
340              Vorinostat  '488976341', '488427907', '488427906', '488427...
341                  XELIRI  '483927056', '483926653', '319346856', '251914...
342                   XELOX  '319408555', '312524939', '175266338', '135264...
343         Ziv-Aflibercept  '481985741', '481101909', '480401320', '381127...
344         Zoledronic Acid  '488428506', '488316176', '488316175', '488316...

[345 rows x 2 columns]

Saved SID_Drug_Info

# The SID in SID_Drug_info.xlsx is used to form a link using esummary to get PubChem_Synonym and source info column and saved in excel file Pubchem_synon.xlsx. Exception SID are saved in Exception_SID.xlsx

In [31]:
def getsynonympubchem(sid):
    sid=sid.replace(" ","").replace("'","")
    #print(sid)
    #print(sid)
    time.sleep(1)
    url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id="+sid+"&retmode=xml"
    print(url)
    result = urllib.request.urlopen(url)
    data= result.read().decode('utf-8')
    entries = xmltodict.parse(data)
    print(entries)
    synonym=[]
    source_info=[]
    Id = entries ['eSummaryResult']['DocSum']['Id']
    #print(Id)
    for entry in entries ['eSummaryResult']['DocSum']['Item']:
        #print(entry)
        define = entry['@Name']
        #print(define)
        if define == 'SynonymList':
            extract=entry['Item']
            print(extract)
            for ext in extract:
                print(ext)
                text = {key: ext[key] for key in ext.keys() & {'#text'}}
                #print(text)
                text = list(text.values())
                text =str(text)[1:-1]
                text=text.replace("'","")
                #print(text)
                synonym.append(text)
        
        elif define == 'SourceNameList':
            extract2 = entry['Item']
            #print(extract2)
            for ext2 in extract2:
                #print(ext2)
                text2 = {key: ext2[key] for key in ext2.keys() & {'#text'}}
                #print(text)
                text2 = list(text2.values())
                text2 =str(text2)[1:-1]
                text2=text2.replace("'","")
                #print(text2)
                source_info.append(text2)
    print(source_info)
    print(synonym)
    print(len(synonym))
    return source_info, synonym
getsynonympubchem("485262066")
getsynonympubchem("485231341")

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485262066&retmode=xml
{'eSummaryResult': {'DocSum': {'Id': '485262066', 'Item': [{'@Name': 'SID', '@Type': 'Integer', '#text': '485262066'}, {'@Name': 'SourceNameList', '@Type': 'List', 'Item': [{'@Name': 'string', '@Type': 'String', '#text': '15699'}, {'@Name': 'string', '@Type': 'String', '#text': 'LGC Standards Product List'}, {'@Name': 'string', '@Type': 'String', '#text': 'LGC Standards'}]}, {'@Name': 'SourceID', '@Type': 'String', '#text': 'TRC-D288080'}, {'@Name': 'SourceCategoryList', '@Type': 'List', 'Item': {'@Name': 'string', '@Type': 'String', '#text': 'Chemical Vendors'}}, {'@Name': 'SourceReleaseDate', '@Type': 'Date', '#text': '2023/12/01 00:00'}, {'@Name': 'DepositDate', '@Type': 'Date', '#text': '2023/12/01 00:00'}, {'@Name': 'ModifyDate', '@Type': 'Date', '#text': '2023/12/01 00:00'}, {'@Name': 'RegistryNumber', '@Type': 'String', '#text': '122914-94-7'}, {'@Name': 'DBUrl', '@Type': 'String', '#text': 'https://www.lgcstandards.com/US/en/'}, {'@Name': 'SBUrl', '@Type': 'String', '#text': 'https://www.lgcstandards.com/CA/en/p/TRC-D288080-250MG'}, {'@Name': 'SynonymList', '@Type': 'List', 'Item': [{'@Name': 'string', '@Type': 'String', '#text': 'Depyridinyl Abiraterone 3-Acetate 17-Hydrazone'}, {'@Name': 'string', '@Type': 'String', '#text': '122914-94-7'}]}, {'@Name': 'MeSHHeadingList', '@Type': 'List'}, {'@Name': 'MeSHTermList', '@Type': 'List'}, {'@Name': 'PharmActionList', '@Type': 'List'}, {'@Name': 'CommentList', '@Type': 'List'}, {'@Name': 'IUPACName', '@Type': 'String'}, {'@Name': 'CanonicalSmile', '@Type': 'String'}, {'@Name': 'RotatableBondCount', '@Type': 'Integer'}, {'@Name': 'MolecularFormula', '@Type': 'String'}, {'@Name': 'MolecularWeight', '@Type': 'String'}, {'@Name': 'TotalFormalCharge', '@Type': 'Integer'}, {'@Name': 'XLogP', '@Type': 'String'}, {'@Name': 'HydrogenBondDonorCount', '@Type': 'Integer'}, {'@Name': 'HydrogenBondAcceptorCount', '@Type': 'Integer'}, {'@Name': 'Complexity', '@Type': 'String'}, {'@Name': 'HeavyAtomCount', '@Type': 'Integer'}, {'@Name': 'AtomChiralCount', '@Type': 'Integer'}, {'@Name': 'AtomChiralDefCount', '@Type': 'Integer'}, {'@Name': 'AtomChiralUndefCount', '@Type': 'Integer'}, {'@Name': 'BondChiralCount', '@Type': 'Integer'}, {'@Name': 'BondChiralDefCount', '@Type': 'Integer'}, {'@Name': 'BondChiralUndefCount', '@Type': 'Integer'}, {'@Name': 'IsotopeAtomCount', '@Type': 'Integer'}, {'@Name': 'CovalentUnitCount', '@Type': 'Integer'}, {'@Name': 'TautomerCount', '@Type': 'Integer'}, {'@Name': 'CompoundIDList', '@Type': 'List', 'Item': {'@Name': 'int', '@Type': 'Integer', '#text': '10198397'}}, {'@Name': 'TPSA', '@Type': 'String'}, {'@Name': 'AssaySourceNameList', '@Type': 'List'}, {'@Name': 'MinAC', '@Type': 'String'}, {'@Name': 'MaxAC', '@Type': 'String'}, {'@Name': 'MinTC', '@Type': 'String'}, {'@Name': 'MaxTC', '@Type': 'String'}, {'@Name': 'ActiveAidCount', '@Type': 'Integer'}, {'@Name': 'InactiveAidCount', '@Type': 'Integer'}, {'@Name': 'TotalAidCount', '@Type': 'Integer', '#text': '0'}, {'@Name': 'InChIKey', '@Type': 'String'}, {'@Name': 'HoldUntilDate', '@Type': 'Date', '#text': '1/01/01 00:00'}]}}}
[{'@Name': 'string', '@Type': 'String', '#text': 'Depyridinyl Abiraterone 3-Acetate 17-Hydrazone'}, {'@Name': 'string', '@Type': 'String', '#text': '122914-94-7'}]
{'@Name': 'string', '@Type': 'String', '#text': 'Depyridinyl Abiraterone 3-Acetate 17-Hydrazone'}
{'@Name': 'string', '@Type': 'String', '#text': '122914-94-7'}
['15699', 'LGC Standards Product List', 'LGC Standards']
['Depyridinyl Abiraterone 3-Acetate 17-Hydrazone', '122914-94-7']
2
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485231341&retmode=xml
{'eSummaryResult': {'DocSum': {'Id': '485231341', 'Item': [{'@Name': 'SID', '@Type': 'Integer', '#text': '485231341'}, {'@Name': 'SourceNameList', '@Type': 'List', 'Item': [{'@Name': 'string', '@Type': 'String', '#text': '15699'}, {'@Name': 'string', '@Type': 'String', '#text': 'LGC Standards Product List'}, {'@Name': 'string', '@Type': 'String', '#text': 'LGC Standards'}]}, {'@Name': 'SourceID', '@Type': 'String', '#text': 'TRC-A108510'}, {'@Name': 'SourceCategoryList', '@Type': 'List', 'Item': {'@Name': 'string', '@Type': 'String', '#text': 'Chemical Vendors'}}, {'@Name': 'SourceReleaseDate', '@Type': 'Date', '#text': '2023/12/01 00:00'}, {'@Name': 'DepositDate', '@Type': 'Date', '#text': '2023/12/01 00:00'}, {'@Name': 'ModifyDate', '@Type': 'Date', '#text': '2023/12/01 00:00'}, {'@Name': 'RegistryNumber', '@Type': 'String'}, {'@Name': 'DBUrl', '@Type': 'String', '#text': 'https://www.lgcstandards.com/US/en/'}, {'@Name': 'SBUrl', '@Type': 'String', '#text': 'https://www.lgcstandards.com/CA/en/p/TRC-A108510-2.5MG'}, {'@Name': 'SynonymList', '@Type': 'List', 'Item': {'@Name': 'string', '@Type': 'String', '#text': 'Abiraterone acetate N-oxide'}}, {'@Name': 'MeSHHeadingList', '@Type': 'List'}, {'@Name': 'MeSHTermList', '@Type': 'List'}, {'@Name': 'PharmActionList', '@Type': 'List'}, {'@Name': 'CommentList', '@Type': 'List'}, {'@Name': 'IUPACName', '@Type': 'String'}, {'@Name': 'CanonicalSmile', '@Type': 'String'}, {'@Name': 'RotatableBondCount', '@Type': 'Integer'}, {'@Name': 'MolecularFormula', '@Type': 'String'}, {'@Name': 'MolecularWeight', '@Type': 'String'}, {'@Name': 'TotalFormalCharge', '@Type': 'Integer'}, {'@Name': 'XLogP', '@Type': 'String'}, {'@Name': 'HydrogenBondDonorCount', '@Type': 'Integer'}, {'@Name': 'HydrogenBondAcceptorCount', '@Type': 'Integer'}, {'@Name': 'Complexity', '@Type': 'String'}, {'@Name': 'HeavyAtomCount', '@Type': 'Integer'}, {'@Name': 'AtomChiralCount', '@Type': 'Integer'}, {'@Name': 'AtomChiralDefCount', '@Type': 'Integer'}, {'@Name': 'AtomChiralUndefCount', '@Type': 'Integer'}, {'@Name': 'BondChiralCount', '@Type': 'Integer'}, {'@Name': 'BondChiralDefCount', '@Type': 'Integer'}, {'@Name': 'BondChiralUndefCount', '@Type': 'Integer'}, {'@Name': 'IsotopeAtomCount', '@Type': 'Integer'}, {'@Name': 'CovalentUnitCount', '@Type': 'Integer'}, {'@Name': 'TautomerCount', '@Type': 'Integer'}, {'@Name': 'CompoundIDList', '@Type': 'List', 'Item': {'@Name': 'int', '@Type': 'Integer', '#text': '129012014'}}, {'@Name': 'TPSA', '@Type': 'String'}, {'@Name': 'AssaySourceNameList', '@Type': 'List'}, {'@Name': 'MinAC', '@Type': 'String'}, {'@Name': 'MaxAC', '@Type': 'String'}, {'@Name': 'MinTC', '@Type': 'String'}, {'@Name': 'MaxTC', '@Type': 'String'}, {'@Name': 'ActiveAidCount', '@Type': 'Integer'}, {'@Name': 'InactiveAidCount', '@Type': 'Integer'}, {'@Name': 'TotalAidCount', '@Type': 'Integer', '#text': '0'}, {'@Name': 'InChIKey', '@Type': 'String'}, {'@Name': 'HoldUntilDate', '@Type': 'Date', '#text': '1/01/01 00:00'}]}}}
{'@Name': 'string', '@Type': 'String', '#text': 'Abiraterone acetate N-oxide'}
@Name

AttributeError: 'str' object has no attribute 'keys'

In [16]:
def getsynpc():
    df=pd.read_excel("SID_Drug_info.xlsx")
    df = df.set_index(['Drug_name']).apply(lambda x: x.str.split(',').explode()).reset_index()
    data_df=pd.DataFrame(columns = ['SID', 'Source_Info', 'PubChem_Synonym'])
    df.to_excel("split_sid_info.xlsx", index=False)
    exception_df=pd.DataFrame(columns=['SID'])
    for sid in df['SID']:
        try:
            source_info, synonym = getsynonympubchem(sid)
            source_info=str(source_info)[2:-2]
            source_info=source_info.replace("'","")
            synonym=str(synonym)[2:-2]
            synonym=synonym.replace("'","")
            data_df = pd.concat([data_df, pd.DataFrame({'SID': [sid], 'Source_Info': [source_info], 'PubChem_Synonym': [synonym]})], ignore_index=True)
        except Exception as e:
            print('Exception_SID:', sid, e)
            exception_df = pd.concat([exception_df, pd.DataFrame({'SID': [sid]})], ignore_index=True)
            
    data_df.to_excel("Final_pubchem.xlsx", index=False)
    display(data_df)
    exception_df.to_excel("Exception_SID.xlsx", index=False)
    print("Sync SID and Synonyms and saved final_pubchem.xlsx")
getsynpc()

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=482042220&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=481101667&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472421408&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472420314&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472419851&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=463820146&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=404719648&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=384585532&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489440693&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489440495&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489355322&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488985212&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488410342&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488406827&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305681&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305680&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305679&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305678&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305677&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305676&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305675&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305674&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488226478&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488226477&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488226476&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488226475&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485960584&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485959909&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488957728&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488318359&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305682&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488224375&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488196332&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485726222&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485653671&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485646392&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485403143&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485396818&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485292499&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485262066&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485231341&retmode=xml
Exception_SID:  '485231341' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485231339&retmode=xml
Exception_SID:  '485231339' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485231338&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485231334&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=483929526&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=483929525&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=483927420&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=483765317&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=135264548&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=135264424&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=127830723&retmode=xml
Exception_SID:  '127830723' 'Item'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=53788214&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=53787204&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=3533476&retmode=xml
Exception_SID: 3533476 'Item'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489597152&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489593309&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489484312&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489441539&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489441322&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489439656&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489439544&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489437393&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489437390&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489436943&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489436469&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489436123&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489435946&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489435364&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489415593&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489389053&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489360478&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489360477&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489360159&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489342386&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489588447&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=489441148&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488406834&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488305689&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488226563&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488202174&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485723374&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485517591&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485480408&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485403647&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485239821&retmode=xml
Exception_SID:  '485239821' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485237138&retmode=xml
Exception_SID:  '485237138' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485231432&retmode=xml
Exception_SID:  '485231432' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485231431&retmode=xml
Exception_SID:  '485231431' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485231430&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=483954342&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=483927701&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=483927700&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=337643545&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=337541984&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=3533569&retmode=xml
Exception_SID: 3533569 'Item'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488425338&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485726264&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=481155381&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=475546922&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472385906&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472264665&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=469690931&retmode=xml
Exception_SID:  '469690931' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=405092064&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=387061215&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=385612250&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=385327557&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=385326041&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=354355060&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=349016747&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=347910344&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=329976997&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=315661178&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=249565679&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=223366123&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=178103463&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485618509&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=483926598&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=483475944&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=482260509&retmode=xml
Exception_SID:  '482260509' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=482107040&retmode=xml
Exception_SID:  '482107040' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=481120663&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472463191&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472175254&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=442141326&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=440200175&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=405560329&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=405243592&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=405055395&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=387191127&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=387190648&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488323207&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485511918&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485483261&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=482586054&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=481101546&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472405637&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472386361&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472225243&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=471145844&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=471144005&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=459143496&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=375973255&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=347910376&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=329976977&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=178103907&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=178103378&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=135300399&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=131277422&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=124490327&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504970&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504961&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504954&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504948&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504942&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504936&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504929&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504922&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504916&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504910&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504904&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504898&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504888&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504881&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504878&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504867&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504861&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504854&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504847&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488504841&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472425630&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=446174156&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=375758853&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=347910224&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=335986980&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=488298020&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=486299803&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485720522&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485618528&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485452538&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=485273077&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=484290968&retmode=xml
Exception_SID:  '484290968' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=484211210&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=482194662&retmode=xml
Exception_SID:  '482194662' 'str' object has no attribute 'keys'
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=481107121&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=478259732&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=475977095&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=475724854&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472952955&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=472454957&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=374912822&retmode=xml
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pcsubstance&id=468589835&retmode=xml

,SID,Source_Info,PubChem_Synonym
0,'482042220',"26136, PubChem Reference Collection","24U06E3FHJ, ANTI-BCMA02 CAR LENTIVIRAL VECTOR,..."
1,'481101667',"26136, PubChem Reference Collection","Ide-cel, idecabtagen vicleucel, ABECMA, Idecab..."
2,'472421408',"2322, FDA Substance Registration System, FDA/S...","H4ON8SV8LK, ANTI-BCMA CAR T RECEPTOR, BB-2121 ..."
3,'472420314',"2322, FDA Substance Registration System, FDA/S...","24U06E3FHJ, ANTI-BCMA02 CAR LENTIVIRAL VECTOR,..."
4,'472419851',"2322, FDA Substance Registration System, FDA/S...","Ide-cel, ABECMA, Idecabtagene vicleucel, Anti-..."
...,...,...,...
4530,'485653895',"MMDB, MMDB, NCBI Protein Structures, NCBI Stru...","Zoledronic acid, ZOL"
4531,'485325631',"15699, LGC Standards Product List, LGC Standards","Zoledronic acid, 118072-93-8"
4532,'485325630',"15699, LGC Standards Product List, LGC Standards","Zoledronic-d3 Acid, 1134798-26-7"
4533,'485325629',"15699, LGC Standards Product List, LGC Standards","Zoledronic Acid-15N2,13C2, 1189694-79-8"
4534,'485325627',"15699, LGC Standards Product List, LGC Standards","165800-07-7, Zoledronic Acid Disodium Salt Tet..."

# Merge the drugname in the file split_sid_info.xlsx and PubChem synonyms in the file Final_pubchem.xlsx to get the column Drug_name and PubChem_Synonym in the file Pubchem_Data.xlsx

In [8]:
def merge():
    sid_list=pd.read_excel("split_sid_info.xlsx")
    display(sid_list)
    pubchem_synon=pd.read_excel("Final_pubchem.xlsx")
    display(pubchem_synon)
    drug_pubchem_synon=pd.merge(sid_list, pubchem_synon, how='inner', on='SID')
    drug_pubchem_synon=drug_pubchem_synon.drop(labels=['SID', 'Source_Info'], axis=1 )
    drug_pubchem_synon = drug_pubchem_synon.groupby('Drug_name')['PubChem_Synonym'].agg(lambda x: ', '.join(set(x))).reset_index()
    drug_pubchem_synon['PubChem_Synonym']=drug_pubchem_synon['PubChem_Synonym'].str.split(', ').apply(set).str.join(', ')
    drug_pubchem_synon.to_excel("Pubchem_Data.xlsx", index=False)
    display(drug_pubchem_synon)
merge()

                   Drug_name           SID
0     Idecabtagene Vicleucel   '482042220'
1     Idecabtagene Vicleucel   '481101667'
2     Idecabtagene Vicleucel   '472421408'
3     Idecabtagene Vicleucel   '472420314'
4     Idecabtagene Vicleucel   '472419851'
...                      ...           ...
5329         Zoledronic Acid   '485244526'
5330         Zoledronic Acid   '482316832'
5331         Zoledronic Acid   '482316831'
5332         Zoledronic Acid   '482316830'
5333         Zoledronic Acid   '482106714'

[5334 rows x 2 columns]

,SID,Source_Info,PubChem_Synonym
0,'482042220',"26136, PubChem Reference Collection","24U06E3FHJ, ANTI-BCMA02 CAR LENTIVIRAL VECTOR,..."
1,'481101667',"26136, PubChem Reference Collection","Ide-cel, idecabtagen vicleucel, ABECMA, Idecab..."
2,'472421408',"2322, FDA Substance Registration System, FDA/S...","H4ON8SV8LK, ANTI-BCMA CAR T RECEPTOR, BB-2121 ..."
3,'472420314',"2322, FDA Substance Registration System, FDA/S...","24U06E3FHJ, ANTI-BCMA02 CAR LENTIVIRAL VECTOR,..."
4,'472419851',"2322, FDA Substance Registration System, FDA/S...","Ide-cel, ABECMA, Idecabtagene vicleucel, Anti-..."
...,...,...,...
4552,'485653895',"MMDB, MMDB, NCBI Protein Structures, NCBI Stru...","Zoledronic acid, ZOL"
4553,'485325631',"15699, LGC Standards Product List, LGC Standards","Zoledronic acid, 118072-93-8"
4554,'485325630',"15699, LGC Standards Product List, LGC Standards","Zoledronic-d3 Acid, 1134798-26-7"
4555,'485325629',"15699, LGC Standards Product List, LGC Standards","Zoledronic Acid-15N2,13C2, 1189694-79-8"
4556,'485325627',"15699, LGC Standards Product List, LGC Standards","165800-07-7, Zoledronic Acid Disodium Salt Tet..."

               Drug_name                                    PubChem_Synonym
0                   ABVD  COPP-ABVD, ABVD protocol, C522158, C034632, AB...
1                     AC  N0001-008068, N0001-002416, N0001-004091, N000...
2                    ADE  BOTOKI V MASK, HSDB 7774, Mioggi Healing Effec...
3            Abemaciclib  LY-2835219, Abemaciclib, BLP-003180, B0084-462...
4    Abiraterone Acetate  Abiraterone acetate (Standard), ABIRATERONE AC...
..                   ...                                                ...
321               XELIRI  Xeliri, IRINOTECAN HYDROCHLORIDE [ORANGE BOOK]...
322                XELOX  CAPECITABINE [USP IMPURITY], Capecitabine Meda...
323         Zanubrutinib  1691249-45-2, 1633350-06-7, (R)-Zanubrutinib, ...
324      Ziv-Aflibercept  Aflibercept (USAN/INN), Vascular Endothelial G...
325      Zoledronic Acid  BLP-007647, Zoledronic Acid-[13C2,d3] Sodium s...

[326 rows x 2 columns]

# MERGE DATA FROM CANCER.GOV and PUBCHEM

In [25]:
def pubchemndncidatamerge():
    drug_info_df=pd.read_excel('NCI_drug_tumor_list_NCI_Thesaurus_Data.xlsx')
    pubchem_info=pd.read_excel('Pubchem_Data.xlsx')
    drug_pubchem_info=pd.merge(drug_info_df, pubchem_info, how='left', on='Drug_name')
    #display(drug_pubchem_info)
    #drug_pubchem_info=pd.merge(drug_pubchem_info, nci_thesaurus_info, how='left', left_on='Drug_name',)
    drug_pubchem_info= drug_pubchem_info.drop_duplicates()
    drug_pubchem_info.to_excel("Final_NCI_PubChem_Drug_Database.xlsx",index=False)
pubchemndncidatamerge()